//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr6_NetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovari
    {
        public string Article { get; set; }
        public string Naimenovanie { get; set; }
        public string Ed_izmerenia { get; set; }
        public Nullable<short> Stoimst { get; set; }
        public Nullable<byte> Razmer_max { get; set; }
        public string Proizvoditel { get; set; }
        public string Postavshik { get; set; }
        public string Kategoria { get; set; }
        public Nullable<byte> Destviushaia_skidka { get; set; }
        public Nullable<byte> Kolvo_na_sklade { get; set; }
        public string Opisanie { get; set; }
        public string Izobrazhenie { get; set; }
    }
}
