//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr6_NetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int id { get; set; }
        public string Sostav_zakaza { get; set; }
        public string Data_zakaza { get; set; }
        public string Data_vidochi { get; set; }
        public int Punkt_vidochi { get; set; }
        public string FIO_clienta { get; set; }
        public Nullable<short> Kod_poluchenia { get; set; }
        public string Status_zakaza { get; set; }
    
        public virtual Punkt_vidachi Punkt_vidachi { get; set; }
    }
}
